version: '3.10'

services:
  backend:
    build: ./backend
    command: >
      sh -c "gunicorn OneCall.wsgi:application --bind 0.0.0.0:8000 --workers 2"
    volumes:
      - ./backend:/usr/src/app/
      - static_volume:/usr/src/app/api/static
      - media_volume:/usr/src/app/api/media
    ports:
      - "8000:8000"
    depends_on:
      - db
      - migration
    networks:
      - backend

  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: onecall
      POSTGRES_USER: bagyshan
      POSTGRES_PASSWORD: 1
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    networks:
      - backend
    
  migration:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: on-failure
    command: >
      sh -c "python manage.py makemigrations && python manage.py migrate"
    volumes:
      - ./backend:/usr/src/app/
    depends_on:
      - db
    networks:
      - backend

  celery:
    build: ./backend
    command: celery -A OneCall worker -l info
    volumes: 
      - ./backend:/usr/src/app/
    depends_on:
      - backend
      - redis
    networks:
      - backend

  redis:
    image: redis
    container_name: "redis"
    ports:
      - "6379:6379"
    networks:
      - backend

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.prod
    container_name: "odinzvonok-nginx"
    restart: always
    volumes:
      - ./nginx/nginx-prod.conf:/etc/nginx/conf.d/nginx-prod.conf
      - /etc/letsencrypt:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
      - nginx_frontend_static_volume:/usr/share/nginx/html
      - static_volume:/usr/src/app/api/static
      - media_volume:/usr/src/app/api/media
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    networks:
      - backend



  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "3000:80"
      # - "3000:443"
    container_name: "frontend"
    volumes:
      - ./frontend/default.conf:/etc/nginx/conf.d/default.conf
      - front_static_volume:/usr/src/app/static
      - static_volume:/usr/src/app/api/static
    environment:
      - NODE_ENV=production
      - REACT_APP_API_URL=http://nginx/api/
    depends_on:
      - backend
    networks:
      - backend



volumes:
  postgres_data:
  static_volume:
  front_static_volume:
  nginx_frontend_static_volume:
  media_volume:

networks:
  backend: