version: '3.10'

services:
  backend:
    build: ./backend
    command: >
      sh -c "gunicorn OneCall.wsgi:application --bind 0.0.0.0:8000 --workers 2"
    volumes:
      - ./backend:/usr/src/app/
      - static_volume:/usr/src/app/api/static
      - media_volume:/usr/src/app/api/media
    ports:
      - "8000:8000"
    depends_on:
      - db
      - migration
    networks:
      - backend

  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: onecall
      POSTGRES_USER: bagyshan
      POSTGRES_PASSWORD: 1
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    networks:
      - backend
    
  migration:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: on-failure
    command: >
      sh -c "python manage.py makemigrations && python manage.py migrate"
    volumes:
      - ./backend:/usr/src/app/
    depends_on:
      - db
    networks:
      - backend

  celery:
    build: ./backend
    command: celery -A OneCall worker -l info
    volumes: 
      - ./backend:/usr/src/app/
    depends_on:
      - backend
      - redis
    networks:
      - backend

  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - backend

  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile.local
    container_name: "nginx"
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx-local.conf:/etc/nginx/conf.d/nginx-local.conf
      - static_volume:/usr/src/app/api/static
      - media_volume:/usr/src/app/api/media
    depends_on:
      - backend
    networks:
      - backend



volumes:
  postgres_data:
  static_volume:
  media_volume:

networks:
  backend: